import 'package:flutter/material.dart';
import 'main.dart';
import 'menu.dart';
void main() {
  runApp(const FigmaToCodeApp2());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp2 extends StatelessWidget {
  const FigmaToCodeApp2({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone1415Pro2(),
        ]),
      ),
    );
  }
}

class Iphone1415Pro2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 852,
                  decoration: BoxDecoration(color: const Color(0xFFBCE2B7)),
                ),
              ),
              Positioned(
                left: 93,
                top: 57,
                child: SizedBox(
                  width: 197,
                  height: 30,
                  child: Text(
                    'Novel',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 23,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 93,
                top: 96,
                child: SizedBox(
                  width: 197,
                  height: 30,
                  child: Text(
                    'List',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 128,
                child: SizedBox(
                  width: 83,
                  height: 26,
                  child: Text(
                    'Favoritos',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF2A5836),
                      fontSize: 20,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 325,
                child: SizedBox(
                  width: 156,
                  height: 23,
                  child: Text(
                    'Recomendados',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF2A5836),
                      fontSize: 20,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 166,
                child: Container(
                  width: 131,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 164,
                top: 166,
                child: Container(
                  width: 131,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 313,
                top: 166,
                child: Container(
                  width: 93,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 379,
                child: Container(
                  width: 131,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 164,
                top: 379,
                child: Container(
                  width: 131,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 313,
                top: 379,
                child: Container(
                  width: 93,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 393,
                child: Container(
                  width: 133,
                  height: 81,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://imgs.search.brave.com/WcyjRp9r8U8g8vFZ86aHT1C8keCRkPzAMYy1TW9lF0w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/ODFwMWFsUWVweEwu/anBn"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 163,
                top: 393,
                child: Container(
                  width: 133,
                  height: 81,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://imgs.search.brave.com/-6xaoF1LW-BFfX6LKG0Ib1r0hkaLmt6OaDFUcXEIOEo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2YzLzZj/L2ZhL2YzNmNmYTg4/MDYzOWUyOWUzMWQw/YWJlNzdmMjE2Njk1/LmpwZw"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 310,
                top: 391,
                child: Container(
                  width: 133,
                  height: 81,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://imgs.search.brave.com/oySfYsl-VwKD8QMQ203wreh40bXvSN57P9p8RmgEP8c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJzLmNvbS9p/bWFnZXMvaGQvdGhl/LWp1bmlvcnMtbW8t/ZGFvLXp1LXNoaS10/ejB0cThucjhjamZm/dzdtLmpwZw"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 780,
                child: Container(
                  width: 393,
                  height: 72,
                  decoration: BoxDecoration(color: const Color(0xFF2E362F)),
                ),
              ),
              Positioned(
                left: 38,
                top: 792,
                child: GestureDetector(
    onTap: () {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => FigmaToCodeApp()),
      );
    },
                child: Container(
                  width: 53,
                  height: 53,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://cdn-icons-png.freepik.com/256/9046/9046092.png?ga=GA1.1.1390340374.1744642370&semt=ais_hybrid"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0x00020202),
                      ),
                    ),
                  ),
                ),
                ),
              ),
              Positioned(
                left: 176,
                top: 792,
                child: GestureDetector(
    onTap: () {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => FigmaToCodeApp2()),
      );
    },
                child: Container(
                  width: 53,
                  height: 53,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://cdn-icons-png.freepik.com/256/615/615254.png?ga=GA1.1.1390340374.1744642370&semt=ais_hybrid"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                ),
              ),
              Positioned(
                left: 306,
                top: 792,
                child: GestureDetector(
    onTap: () {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => FigmaToCodeApp3()),
      );
    },
                child: Container(
                  width: 53,
                  height: 53,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://cdn-icons-png.freepik.com/256/9073/9073315.png?ga=GA1.1.1390340374.1744642370&semt=ais_hybrid"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                ),
              ),
              Positioned(
                left: 151,
                top: 784,
                child: Container(
                  width: 102,
                  height: 4,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}