import 'package:flutter/material.dart';
import 'main.dart';
import 'favorite.dart';
void main() {
  runApp(const FigmaToCodeApp3());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp3 extends StatelessWidget {
  const FigmaToCodeApp3({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone1415Pro3(),
        ]),
      ),
    );
  }
}

class Iphone1415Pro3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 852,
                  decoration: BoxDecoration(color: const Color(0xFFBCE2B7)),
                ),
              ),
              Positioned(
                left: 93,
                top: 67,
                child: SizedBox(
                  width: 197,
                  height: 30,
                  child: Text(
                    'Novel',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 23,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 93,
                top: 96,
                child: SizedBox(
                  width: 197,
                  height: 30,
                  child: Text(
                    'List',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 780,
                child: Container(
                  width: 393,
                  height: 72,
                  decoration: BoxDecoration(color: const Color(0xFF2E362F)),
                ),
              ),
              Positioned(
                left: 38,
                top: 792,
                child: GestureDetector(
    onTap: () {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => FigmaToCodeApp()),
      );
    },
                child: Container(
                  width: 53,
                  height: 53,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://cdn-icons-png.freepik.com/256/9046/9046092.png?ga=GA1.1.1390340374.1744642370&semt=ais_hybrid"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0x00020202),
                      ),
                    ),
                  ),
                ),
                ),
              ),
              Positioned(
                left: 176,
                top: 792,
                child: GestureDetector(
    onTap: () {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => FigmaToCodeApp2()),
      );
    },
                child: Container(
                  width: 53,
                  height: 53,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://cdn-icons-png.freepik.com/256/615/615254.png?ga=GA1.1.1390340374.1744642370&semt=ais_hybrid"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                ),
              ),
              Positioned(
                left: 306,
                top: 792,
                child: GestureDetector(
    onTap: () {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => FigmaToCodeApp3()),
      );
    },
                child: Container(
                  width: 53,
                  height: 53,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://cdn-icons-png.freepik.com/256/9073/9073315.png?ga=GA1.1.1390340374.1744642370&semt=ais_hybrid"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                ),
              ),
              Positioned(
                left: 93,
                top: 569,
                child: Container(
                  width: 56,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF3E3D3D),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 234,
                top: 569,
                child: Container(
                  width: 56,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF3E3D3D),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 126,
                top: 342,
                child: SizedBox(
                  width: 150,
                  height: 25,
                  child: Text(
                    'Configurações',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF024023),
                      fontSize: 20,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 126,
                top: 419,
                child: SizedBox(
                  width: 150,
                  height: 25,
                  child: Text(
                    'Notificações',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF024023),
                      fontSize: 20,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 121,
                top: 494,
                child: SizedBox(
                  width: 150,
                  height: 25,
                  child: Text(
                    'Encerrar Sessão',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF024023),
                      fontSize: 20,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 165,
                child: Container(
                  width: 115,
                  height: 70,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/115x70"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 334,
                child: Container(
                  width: 68,
                  height: 41,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/68x41"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 412,
                child: Container(
                  width: 66,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/66x40"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 490,
                child: Container(
                  width: 65,
                  height: 39,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/65x39"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 86,
                top: 576,
                child: Container(
                  width: 70,
                  height: 42,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/70x42"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 227,
                top: 576,
                child: Container(
                  width: 70,
                  height: 42,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/70x42"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}